name: Release

# This workflow uses Release Please to automatically analyze
# and create a release PR when a commit is pushed to the main branch.

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Analyse commits and open PR or prepare release 📦
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # We need to use PAT in order to trigger the release workflow
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          release-type: node
          package-name: pubsub-http-handler
