name: Weekly jobs
on:
  workflow_dispatch:
  schedule:
    # Runs every Monday at 12
    - cron: '0 12 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - run: yarn install

      - name: Run typegen
        run: yarn run generate:docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-documentation
          delete-branch: true
          commit-message: 'chore(docs): run typegen'
          title: 'chore(docs): run typegen'
          body: 'This is automatically created by weekly scheduled jobs.'
