name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - run: yarn install
      - run: yarn run test
      - run: yarn run build
      - uses: codecov/codecov-action@v5
